[profile.default]
  fs_permissions = [{ access = "read-write", path = "./" }]
  optimizer = true
  optimizer-runs = 10_000_000
  solc-version = "0.8.19"
  verbosity = 3

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 100
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "single"
  tab_width = 2
  wrap_comments = true

[rpc_endpoints]
  arbitrum = "${ARBITRUM_ONE_RPC_URL}"
  goerli = "${GOERLI_RPC_URL}"
  mainnet = "${MAINNET_RPC_URL}"
  optimism = "${OPTIMISM_RPC_URL}"
  polygon = "${POLYGON_RPC_URL}"
  sepolia = "${SEPOLIA_RPC_URL}"
