[profile.default]
  fs_permissions = [{ access = "read-write", path = "./" }]
  optimizer = false                                         # faster compilation
  optimizer-runs = 10_000_000
  solc-version = "0.8.15"

[profile.default.fmt]
  bracket_spacing = false
  int_types = 'short'
  line_length = 80
  multiline_func_header = 'attributes_first'
  number_underscore = 'thousands'
  quote_style = 'double'
  single_line_statement_blocks = 'single'
  tab_width = 2
